apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
        - name: codeserver-proxy-container
          image: poridhi/codeserver-reverse-proxy:v1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000