apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codeserver-proxy-tunnel
  name: codeserver-proxy-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver-proxy-tunnel
  template:
    metadata:
      labels:
        app: codeserver-proxy-tunnel
    spec:
      containers:
      - name: codeserver-proxy-tunnel
        image: cloudflare/cloudflared:latest
        # image: ghcr.io/maggie0002/cloudflared:2022.7.1
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=eyJhIjoiZGMwMTdkY2RkOWZiOTMzMmJjNTRhNDgxODIwYjhlMjYiLCJ0IjoiY2M3MjhiZGEtMjhiYi00MDVhLWJlYjYtNjQ1M2ZiMjEwYjM1IiwicyI6Ik1EVmlPREZsTmpVdE16UTFOaTAwWmpoaExXRXhaVFV0TUdZd09XWTVZMlU0WVRGaiJ9"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 60