apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codeserver-proxy-tunnel
  name: codeserver-proxy-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver-proxy-tunnel
  template:
    metadata:
      labels:
        app: codeserver-proxy-tunnel
    spec:
      containers:
      - name: codeserver-proxy-tunnel
        image: cloudflare/cloudflared:latest
        # image: ghcr.io/maggie0002/cloudflared:2022.7.1
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=eyJhIjoiZGMwMTdkY2RkOWZiOTMzMmJjNTRhNDgxODIwYjhlMjYiLCJ0IjoiNjMxZjRjZmQtZGVlZi00YjM0LThkZjYtY2Q4NzM0MjgwOGY0IiwicyI6IlpHSTFaV0k1TldRdFltRm1NaTAwTXpneExUZzJaalV0TldGak1HWmlaalpoTm1aayJ9"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 60