apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codeserver-tunnel
  name: codeserver-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver-tunnel
  template:
    metadata:
      labels:
        app: codeserver-tunnel
    spec:
      containers:
      - name: codeserver-tunnel
        image: cloudflare/cloudflared:latest
        # image: ghcr.io/maggie0002/cloudflared:2022.7.1
        imagePullPolicy: Always
        args: ["tunnel", "--no-autoupdate", "run", "--token=eyJhIjoiZGMwMTdkY2RkOWZiOTMzMmJjNTRhNDgxODIwYjhlMjYiLCJ0IjoiOGQ1OTlkZDEtOWYwZi00YTBjLWJlZTctODVjZTI2N2NiN2JjIiwicyI6Ik1qTTFNRGMwT1RrdE4yVTBOUzAwTm1ZMExXSXpZalV0WXpBeU5UYzVZemc1WWpObSJ9"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 60