apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server-container
          image: poridhi/demo-code-server:v8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-deployment
  namespace: default
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
