FROM codercom/code-server:latest

USER root

RUN rm -rf /var/lib/apt/lists/*

RUN apt update -y 

# Install Runtime and other utils
RUN apt install -y \ 
    curl \
    python3 \
    python3-pip \
    python3-venv 


# Copy your configuration files
COPY ./config /root/.config
COPY ./local /root/.local

# Copy your application code
COPY ./app /app

EXPOSE 8080

WORKDIR /app

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "--disable-telemetry"]